#!/usr/bin/env bash

sudo apt-get update -y

sudo apt-get install curl gnupg2 -y

echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | \
  sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
  sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

sudo apt-get update -y
sudo apt-get upgrade -y

# install packages I use
sudo apt-get install -y whois dnsutils zsh strace clang tcpdump mosh nmap rsync cmake parallel gdb zip unzip docker.io imagemagick golang-go pv sysstat units socat software-properties-common apt-src ack python3-pip python3-dev python3-venv libssl-dev automake keychain psmisc neovim uuid jq apt-transport-https ca-certificates gnupg google-cloud-cli kubectl
